#version 450 core

#include "bvh.glsl"
#include "ao.glsl"

layout(local_size_x = 16, local_size_y = 16) in;

layout(binding = 0) uniform sampler2D gPosition;
layout(binding = 5) uniform sampler2D gNormal;

layout(r32f, binding = 1) uniform image2D aoMask;

void main()
{
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);

    ivec2 size = imageSize(aoMask);

    if(pixel.x >= size.x || pixel.y >= size.y)
        return;

    vec3 fragPos = texelFetch(gPosition, pixel, 0).xyz;
    vec3 normal = normalize(texelFetch(gNormal, pixel, 0).xyz);

    float ao = computeAO(
        fragPos,
        normal
    );

    imageStore(aoMask, pixel, vec4(ao, 0.0, 0.0, 1.0));
}