#version 450 core

layout(local_size_x = 16, local_size_y = 16) in;

layout(binding = 0) uniform sampler2D gPosition;
layout(binding = 1) uniform sampler2D gNormal;
layout(binding = 4) uniform sampler2D gReflectivity;

layout(rgba16f,binding=0) uniform image2D reflectionTexture;


uniform vec3 viewPos;


#include "bvh.glsl"
#include "shadows.glsl"
#include "lighting.glsl"

#define MAX_BOUNCES 3


vec3 traceReflection(vec3 origin, vec3 direction)
{
    vec3 result = vec3(0.0);
    vec3 throughput = vec3(1.0);

    for(int bounce = 0; bounce < MAX_BOUNCES; bounce++)
    {
        int hitObject;
        float hitDistance;
        vec3 hitNormal;

        if(!traverseBVH(origin, direction, 100.0, hitObject, hitDistance, hitNormal))
            break;

        vec3 hitPos = origin + direction * hitDistance;

        vec3 baseColor = objects[hitObject].color.rgb;
        float emission = objects[hitObject].emission;
        
        float refl = objects[hitObject].reflectivity;
        if(emission > 0.0)
        {
            result += throughput * baseColor * emission;
            break;
        }
        float shadow = computeShadow(hitPos, hitNormal);


        vec3 direct = evaluateLighting(
            hitPos,
            hitNormal,
            baseColor,
            vec3(0.0),
            refl,
            hitPos - direction,
            shadow
        ).color;

        result += throughput * direct;

        if(refl <= 0.0)
            break;
        throughput *= refl;

        direction = normalize(reflect(direction, hitNormal));
        origin = hitPos + hitNormal * 0.05;
    }

    return result;
}



void main()
{
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(reflectionTexture);
    if(pixel.x >= size.x || pixel.y >= size.y)
        return;

    vec3 fragPos = texelFetch(gPosition,pixel,0).rgb;
    vec3 normal = normalize(texelFetch(gNormal,pixel,0).rgb);
    float reflectivity = texelFetch(gReflectivity,pixel,0).r;

    if(reflectivity <= 0.0)
    {
        imageStore(reflectionTexture,pixel,vec4(0));
        return;
    }

    vec3 viewDir = normalize(viewPos-fragPos);
    vec3 reflectionDir = normalize(reflect(-viewDir,normal));
    vec3 origin = fragPos + normal * 0.05;

    vec3 color = traceReflection(origin,reflectionDir);

    imageStore(
        reflectionTexture,
        pixel,
        vec4(color*reflectivity,1.0)
    );
}